from enum import IntEnum


class TiError(IntEnum):
    """Errors reported by the Taichi C-API."""

    TI_ERROR_SUCCESS = 0
    TI_ERROR_NOT_SUPPORTED = -1
    TI_ERROR_CORRUPTED_DATA = -2
    TI_ERROR_NAME_NOT_FOUND = -3
    TI_ERROR_INVALID_ARGUMENT = -4
    TI_ERROR_ARGUMENT_NULL = -5
    TI_ERROR_ARGUMENT_OUT_OF_RANGE = -6
    TI_ERROR_ARGUMENT_NOT_FOUND = -7
    TI_ERROR_INVALID_INTEROP = -8
    TI_ERROR_INVALID_STATE = -9
    TI_ERROR_INCOMPATIBLE_MODULE = -10
    TI_ERROR_OUT_OF_MEMORY = -11
    TI_ERROR_MAX_ENUM = 0xffffffff


class TiArch(IntEnum):
    """Types of backend archs."""

    TI_ARCH_RESERVED = 0
    TI_ARCH_VULKAN = 1
    TI_ARCH_METAL = 2
    TI_ARCH_CUDA = 3
    TI_ARCH_X64 = 4
    TI_ARCH_ARM64 = 5
    TI_ARCH_OPENGL = 6
    TI_ARCH_GLES = 7
    TI_ARCH_MAX_ENUM = 0xffffffff


class TiCapability(IntEnum):
    """Device capabilities."""

    TI_CAPABILITY_RESERVED = 0
    TI_CAPABILITY_SPIRV_VERSION = 1
    TI_CAPABILITY_SPIRV_HAS_INT8 = 2
    TI_CAPABILITY_SPIRV_HAS_INT16 = 3
    TI_CAPABILITY_SPIRV_HAS_INT64 = 4
    TI_CAPABILITY_SPIRV_HAS_FLOAT16 = 5
    TI_CAPABILITY_SPIRV_HAS_FLOAT64 = 6
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_INT64 = 7
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_FLOAT16 = 8
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_FLOAT16_ADD = 9
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_FLOAT16_MINMAX = 10
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_FLOAT = 11
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_FLOAT_ADD = 12
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_FLOAT_MINMAX = 13
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_FLOAT64 = 14
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_FLOAT64_ADD = 15
    TI_CAPABILITY_SPIRV_HAS_ATOMIC_FLOAT64_MINMAX = 16
    TI_CAPABILITY_SPIRV_HAS_VARIABLE_PTR = 17
    TI_CAPABILITY_SPIRV_HAS_PHYSICAL_STORAGE_BUFFER = 18
    TI_CAPABILITY_SPIRV_HAS_SUBGROUP_BASIC = 19
    TI_CAPABILITY_SPIRV_HAS_SUBGROUP_VOTE = 20
    TI_CAPABILITY_SPIRV_HAS_SUBGROUP_ARITHMETIC = 21
    TI_CAPABILITY_SPIRV_HAS_SUBGROUP_BALLOT = 22
    TI_CAPABILITY_SPIRV_HAS_NON_SEMANTIC_INFO = 23
    TI_CAPABILITY_SPIRV_HAS_NO_INTEGER_WRAP_DECORATION = 24
    TI_CAPABILITY_MAX_ENUM = 0xffffffff


class TiDataType(IntEnum):
    """Description placeholder"""

    TI_DATA_TYPE_F16 = 0
    TI_DATA_TYPE_F32 = 1
    TI_DATA_TYPE_F64 = 2
    TI_DATA_TYPE_I8 = 3
    TI_DATA_TYPE_I16 = 4
    TI_DATA_TYPE_I32 = 5
    TI_DATA_TYPE_I64 = 6
    TI_DATA_TYPE_U1 = 7
    TI_DATA_TYPE_U8 = 8
    TI_DATA_TYPE_U16 = 9
    TI_DATA_TYPE_U32 = 10
    TI_DATA_TYPE_U64 = 11
    TI_DATA_TYPE_GEN = 12
    TI_DATA_TYPE_UNKNOWN = 13
    TI_DATA_TYPE_MAX_ENUM = 0xffffffff


class TiArgumentType(IntEnum):
    """Description placeholder"""

    TI_ARGUMENT_TYPE_I32 = 0
    TI_ARGUMENT_TYPE_F32 = 1
    TI_ARGUMENT_TYPE_NDARRAY = 2
    TI_ARGUMENT_TYPE_TEXTURE = 3
    TI_ARGUMENT_TYPE_SCALAR = 4
    TI_ARGUMENT_TYPE_MAX_ENUM = 0xffffffff


class TiMemoryUsageFlagBits(IntEnum):
    """Usages of a memory allocation.
    Taichi requires kernel argument memories to be allocated with TI_MEMORY_USAGE_STORAGE_BIT."""

    TI_MEMORY_USAGE_STORAGE_BIT = 1 << 0
    """The memory can be read/write accessed by any kernel."""

    TI_MEMORY_USAGE_UNIFORM_BIT = 1 << 1
    """The memory can be used as a uniform buffer in graphics pipelines."""

    TI_MEMORY_USAGE_VERTEX_BIT = 1 << 2
    """The memory can be used as a vertex buffer in graphics pipelines."""

    TI_MEMORY_USAGE_INDEX_BIT = 1 << 3
    """The memory can be used as an index buffer in graphics pipelines."""


class TiMemoryUsageFlags(IntEnum):
    TI_MEMORY_USAGE_STORAGE_BIT = TiMemoryUsageFlagBits.TI_MEMORY_USAGE_STORAGE_BIT
    TI_MEMORY_USAGE_UNIFORM_BIT = TiMemoryUsageFlagBits.TI_MEMORY_USAGE_UNIFORM_BIT
    TI_MEMORY_USAGE_VERTEX_BIT = TiMemoryUsageFlagBits.TI_MEMORY_USAGE_VERTEX_BIT
    TI_MEMORY_USAGE_INDEX_BIT = TiMemoryUsageFlagBits.TI_MEMORY_USAGE_INDEX_BIT


class TiImageUsageFlagBits(IntEnum):
    """Description placeholder"""

    TI_IMAGE_USAGE_STORAGE_BIT = 1 << 0
    TI_IMAGE_USAGE_SAMPLED_BIT = 1 << 1
    TI_IMAGE_USAGE_ATTACHMENT_BIT = 1 << 2


class TiImageUsageFlags(IntEnum):
    """Description placeholder"""

    TI_IMAGE_USAGE_STORAGE_BIT = TiImageUsageFlagBits.TI_IMAGE_USAGE_STORAGE_BIT
    TI_IMAGE_USAGE_SAMPLED_BIT = TiImageUsageFlagBits.TI_IMAGE_USAGE_SAMPLED_BIT
    TI_IMAGE_USAGE_ATTACHMENT_BIT = TiImageUsageFlagBits.TI_IMAGE_USAGE_ATTACHMENT_BIT


class TiImageDimension(IntEnum):
    """Description placeholder"""

    TI_IMAGE_DIMENSION_1D = 0
    TI_IMAGE_DIMENSION_2D = 1
    TI_IMAGE_DIMENSION_3D = 2
    TI_IMAGE_DIMENSION_1D_ARRAY = 3
    TI_IMAGE_DIMENSION_2D_ARRAY = 4
    TI_IMAGE_DIMENSION_CUBE = 5
    TI_IMAGE_DIMENSION_MAX_ENUM = 0xffffffff


class TiImageLayout(IntEnum):
    """Description placeholder"""

    TI_IMAGE_LAYOUT_UNDEFINED = 0
    TI_IMAGE_LAYOUT_SHADER_READ = 1
    TI_IMAGE_LAYOUT_SHADER_WRITE = 2
    TI_IMAGE_LAYOUT_SHADER_READ_WRITE = 3
    TI_IMAGE_LAYOUT_COLOR_ATTACHMENT = 4
    TI_IMAGE_LAYOUT_COLOR_ATTACHMENT_READ = 5
    TI_IMAGE_LAYOUT_DEPTH_ATTACHMENT = 6
    TI_IMAGE_LAYOUT_DEPTH_ATTACHMENT_READ = 7
    TI_IMAGE_LAYOUT_TRANSFER_DST = 8
    TI_IMAGE_LAYOUT_TRANSFER_SRC = 9
    TI_IMAGE_LAYOUT_PRESENT_SRC = 10
    TI_IMAGE_LAYOUT_MAX_ENUM = 0xffffffff


class TiFormat(IntEnum):
    """Description placeholder"""

    TI_FORMAT_UNKNOWN = 0
    TI_FORMAT_R8 = 1
    TI_FORMAT_RG8 = 2
    TI_FORMAT_RGBA8 = 3
    TI_FORMAT_RGBA8SRGB = 4
    TI_FORMAT_BGRA8 = 5
    TI_FORMAT_BGRA8SRGB = 6
    TI_FORMAT_R8U = 7
    TI_FORMAT_RG8U = 8
    TI_FORMAT_RGBA8U = 9
    TI_FORMAT_R8I = 10
    TI_FORMAT_RG8I = 11
    TI_FORMAT_RGBA8I = 12
    TI_FORMAT_R16 = 13
    TI_FORMAT_RG16 = 14
    TI_FORMAT_RGB16 = 15
    TI_FORMAT_RGBA16 = 16
    TI_FORMAT_R16U = 17
    TI_FORMAT_RG16U = 18
    TI_FORMAT_RGB16U = 19
    TI_FORMAT_RGBA16U = 20
    TI_FORMAT_R16I = 21
    TI_FORMAT_RG16I = 22
    TI_FORMAT_RGB16I = 23
    TI_FORMAT_RGBA16I = 24
    TI_FORMAT_R16F = 25
    TI_FORMAT_RG16F = 26
    TI_FORMAT_RGB16F = 27
    TI_FORMAT_RGBA16F = 28
    TI_FORMAT_R32U = 29
    TI_FORMAT_RG32U = 30
    TI_FORMAT_RGB32U = 31
    TI_FORMAT_RGBA32U = 32
    TI_FORMAT_R32I = 33
    TI_FORMAT_RG32I = 34
    TI_FORMAT_RGB32I = 35
    TI_FORMAT_RGBA32I = 36
    TI_FORMAT_R32F = 37
    TI_FORMAT_RG32F = 38
    TI_FORMAT_RGB32F = 39
    TI_FORMAT_RGBA32F = 40
    TI_FORMAT_DEPTH16 = 41
    TI_FORMAT_DEPTH24STENCIL8 = 42
    TI_FORMAT_DEPTH32F = 43
    TI_FORMAT_MAX_ENUM = 0xffffffff


class TiFilter(IntEnum):
    """Description placeholder"""

    TI_FILTER_NEAREST = 0
    TI_FILTER_LINEAR = 1
    TI_FILTER_MAX_ENUM = 0xffffffff


class TiAddressMode(IntEnum):
    """Description placeholder"""

    TI_ADDRESS_MODE_REPEAT = 0
    TI_ADDRESS_MODE_MIRRORED_REPEAT = 1
    TI_ADDRESS_MODE_CLAMP_TO_EDGE = 2
    TI_ADDRESS_MODE_MAX_ENUM = 0xffffffff